import { act, renderHook, waitFor } from "@testing-library/react";
import { beforeEach, expect, it, vi } from "vitest";
import { apiClient } from "../../lib/apiClient";
import { useQuiz } from "./useQuiz";
vi.mock("../../lib/apiClient", () => ({ apiClient: { get: vi.fn(), post: vi.fn() } }));
const question = { id: "q1", text: "問題", choices: ["A", "B"], category: "technology", timeLimitSec: 90 };
const progress = { categories: [], streakDays: 1 };
beforeEach(() => {
  vi.resetAllMocks();
  vi.mocked(apiClient.get).mockImplementation(async (path) => path.includes("progress") ? progress : question);
  vi.mocked(apiClient.post).mockResolvedValue({ correct: true, correctIndex: 0, explanation: "説明" });
});
it("回答・進捗更新・分野別の次問", async () => {
  const { result } = renderHook(useQuiz);
  await act(async () => result.current.submitAnswer());
  await waitFor(() => expect(result.current.question).toEqual(question));
  await act(async () => result.current.submitAnswer());
  expect(apiClient.post).not.toHaveBeenCalled();
  act(() => result.current.selectChoice(0));
  await act(async () => result.current.submitAnswer());
  expect(result.current.result?.correct).toBe(true);
  act(() => result.current.selectChoice(1));
  expect(result.current.selectedIndex).toBe(0);
  await act(async () => result.current.submitAnswer());
  expect(apiClient.post).toHaveBeenCalledTimes(1);
  await act(async () => result.current.nextQuestion());
  expect(apiClient.get).toHaveBeenCalledWith("/api/quiz/next?excludeId=q1");
  act(() => result.current.selectCategory("technology"));
  await waitFor(() => expect(result.current.question).toEqual(question));
  expect(apiClient.get).toHaveBeenCalledWith("/api/quiz/next?category=technology&excludeId=q1");
  await act(async () => result.current.nextQuestion());
  expect(result.current.categoryFilter).toBe("technology");
});
it("取得・回答エラーから再試行", async () => {
  vi.mocked(apiClient.get).mockRejectedValueOnce(new Error()).mockRejectedValueOnce(new Error());
  const { result } = renderHook(useQuiz);
  await waitFor(() => expect(result.current.error).toContain("取得"));
  await act(async () => result.current.nextQuestion());
  act(() => result.current.selectChoice(0));
  vi.mocked(apiClient.post).mockRejectedValueOnce(new Error());
  await act(async () => result.current.submitAnswer());
  expect(result.current.error).toContain("回答");
  expect(result.current.submitting).toBe(false);
});
it.each([false, true])("古い問題の応答を破棄 %s", async (failed) => {
  let finish!: (value: unknown) => void;
  vi.mocked(apiClient.get).mockImplementationOnce(async () => progress).mockImplementationOnce(() => new Promise((resolve, reject) => { finish = failed ? reject : resolve; }));
  const { result } = renderHook(useQuiz);
  act(() => result.current.selectCategory("strategy"));
  await waitFor(() => expect(result.current.question).toEqual(question));
  await act(async () => finish(failed ? new Error() : { ...question, id: "old" }));
  expect(result.current.question?.id).toBe("q1");
  expect(result.current.error).toBeNull();
});
it.each([false, true])("アンマウント後の進捗取得を破棄 %s", async (failed) => {
  let finish!: (value: unknown) => void;
  vi.mocked(apiClient.get).mockImplementationOnce(() => new Promise((resolve, reject) => { finish = failed ? reject : resolve; }));
  const { unmount } = renderHook(useQuiz);
  unmount();
  await act(async () => finish(failed ? new Error() : progress));
});
it("二重回答・送信中の選択と古い回答を抑止", async () => {
  const { result } = renderHook(useQuiz);
  await waitFor(() => expect(result.current.question).toEqual(question));
  act(() => result.current.selectChoice(0));
  let finish!: (value: unknown) => void;
  vi.mocked(apiClient.post).mockImplementationOnce(() => new Promise((resolve) => { finish = resolve; }));
  let pending!: Promise<void>;
  act(() => { pending = result.current.submitAnswer(); });
  act(() => result.current.selectChoice(1));
  await act(async () => result.current.submitAnswer());
  expect(result.current.selectedIndex).toBe(0);
  await act(async () => result.current.nextQuestion());
  await act(async () => { finish({ correct: true }); await pending; });
  expect(result.current.result).toBeNull();
});
it("古い回答の失敗を表示しない", async () => {
  const { result } = renderHook(useQuiz);
  await waitFor(() => expect(result.current.question).toEqual(question));
  act(() => result.current.selectChoice(0));
  let fail!: () => void;
  vi.mocked(apiClient.post).mockImplementationOnce(() => new Promise((_resolve, reject) => { fail = () => reject(new Error()); }));
  let pending!: Promise<void>;
  act(() => { pending = result.current.submitAnswer(); });
  await act(async () => result.current.nextQuestion());
  await act(async () => { fail(); await pending; });
  expect(result.current.error).toBeNull();
});
it("回答後の古い進捗を表示しない", async () => {
  const { result } = renderHook(useQuiz);
  await waitFor(() => expect(result.current.question).toEqual(question));
  act(() => result.current.selectChoice(0));
  let finish!: (value: unknown) => void;
  vi.mocked(apiClient.get).mockImplementationOnce(() => new Promise((resolve) => { finish = resolve; }));
  let pending!: Promise<void>;
  act(() => { pending = result.current.submitAnswer(); });
  await waitFor(() => expect(result.current.result?.correct).toBe(true));
  await act(async () => result.current.nextQuestion());
  await act(async () => { finish({ categories: [], streakDays: 99 }); await pending; });
  expect(result.current.progress?.streakDays).toBe(1);
});
