import { act, renderHook, waitFor } from "@testing-library/react";
import { beforeEach, expect, it, vi } from "vitest";
import { apiClient } from "../../lib/apiClient";
import { useOjt } from "./useOjt";
vi.mock("../../lib/apiClient", () => ({ apiClient: { get: vi.fn(), post: vi.fn() } }));
const departments = [{ id: "dev", name: "開発" }, { id: "sales", name: "営業" }];
beforeEach(() => {
  vi.resetAllMocks();
  vi.mocked(apiClient.get).mockImplementation(async (path) => path.endsWith("departments") ? { departments } : path.endsWith("messages") ? { messages: [], escalated: false } : { items: [] });
  vi.mocked(apiClient.post).mockResolvedValue({ id: "reply", role: "bot", text: "回答", references: [] });
});
it("課選択・送信・相談・復元・一覧へ戻る", async () => {
  const { result } = renderHook(useOjt);
  await waitFor(() => expect(result.current.departments).toHaveLength(2));
  await act(async () => { await result.current.sendMessage("未選択"); await result.current.escalate(); });
  expect(apiClient.post).not.toHaveBeenCalled();
  await act(async () => result.current.selectDept("dev"));
  expect(result.current.selectedDept?.id).toBe("dev");
  act(() => result.current.setInput("質問"));
  await act(async () => result.current.sendMessage(" "));
  await act(async () => result.current.sendMessage("質問"));
  expect(result.current.messages).toHaveLength(2);
  expect(result.current.input).toBe("");
  await act(async () => result.current.escalate());
  expect(result.current.escalated).toBe(true);
  await act(async () => result.current.escalate());
  expect(apiClient.post).toHaveBeenCalledTimes(2);
  act(() => result.current.backToDeptList());
  expect(result.current.selectedDept).toBeNull();
  expect(result.current.messages).toEqual([]);
});
it("取得と送信・相談失敗を表示し入力を保持", async () => {
  vi.mocked(apiClient.get).mockRejectedValueOnce(new Error());
  const { result } = renderHook(useOjt);
  await waitFor(() => expect(result.current.error).toContain("課一覧"));
  vi.mocked(apiClient.get).mockRejectedValueOnce(new Error());
  await act(async () => result.current.selectDept("dev"));
  expect(result.current.error).toContain("会話");
  await act(async () => result.current.selectDept("dev"));
  act(() => result.current.setInput("質問"));
  vi.mocked(apiClient.post).mockRejectedValue(new Error());
  await act(async () => result.current.sendMessage("質問"));
  expect(result.current.error).toContain("送信");
  expect(result.current.input).toBe("質問");
  await act(async () => result.current.escalate());
  expect(result.current.error).toContain("相談");
});
it.each([false, true])("古い課選択を破棄 %s", async (failed) => {
  const { result } = renderHook(useOjt);
  await waitFor(() => expect(result.current.departments).toHaveLength(2));
  let finish!: (value: unknown) => void;
  vi.mocked(apiClient.get).mockImplementationOnce(() => new Promise((resolve, reject) => { finish = failed ? reject : resolve; }));
  let selection!: Promise<void>;
  act(() => { selection = result.current.selectDept("dev"); });
  await act(async () => result.current.selectDept("sales"));
  await act(async () => { finish(failed ? new Error() : { messages: [{ id: "old" }], escalated: false }); await selection; });
  expect(result.current.selectedDept?.id).toBe("sales");
  expect(result.current.messages).toEqual([]);
  expect(result.current.error).toBeNull();
});
it.each(["send", "escalate"])("操作中の二重要求と課変更を処理 %s", async (action) => {
  const { result } = renderHook(useOjt);
  await waitFor(() => expect(result.current.departments).toHaveLength(2));
  await act(async () => result.current.selectDept("dev"));
  let finish!: (value: unknown) => void;
  vi.mocked(apiClient.post).mockImplementationOnce(() => new Promise((resolve) => { finish = resolve; }));
  let pending!: Promise<void>;
  act(() => { pending = action === "send" ? result.current.sendMessage("質問") : result.current.escalate(); });
  await act(async () => { await result.current.sendMessage("重複"); await result.current.escalate(); });
  await act(async () => result.current.selectDept("sales"));
  await act(async () => { finish({ id: "old", text: "古い" }); await pending; });
  expect(result.current.messages).toEqual([]);
  expect(result.current.escalated).toBe(false);
});
it.each(["send", "escalate"])("別課へ切替後の失敗を表示しない %s", async (action) => {
  const { result } = renderHook(useOjt);
  await waitFor(() => expect(result.current.departments).toHaveLength(2));
  await act(async () => result.current.selectDept("dev"));
  let reject!: () => void;
  vi.mocked(apiClient.post).mockImplementationOnce(() => new Promise((_resolve, fail) => { reject = () => fail(new Error()); }));
  let pending!: Promise<void>;
  act(() => { pending = action === "send" ? result.current.sendMessage("質問") : result.current.escalate(); });
  act(() => result.current.backToDeptList());
  await act(async () => { reject(); await pending; });
  expect(result.current.error).toBeNull();
});
it.each([false, true])("課一覧の遅延応答を破棄 %s", async (failed) => {
  let finish!: (value: unknown) => void;
  vi.mocked(apiClient.get).mockImplementationOnce(() => new Promise((resolve, reject) => { finish = failed ? reject : resolve; }));
  const { unmount } = renderHook(useOjt);
  unmount();
  await act(async () => finish(failed ? new Error() : { departments }));
});
